name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
  COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
  DOCKER_REGISTRY_URL: harbor.artichokenetwork.com
  DOCKER_REPO: landing
  DOCKER_IMAGE_NAME: web

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Build and Push
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest --tag ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:$(date +%d-%m-%Y)
          docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }} --all-tags 

      - name: Sign the Docker Image with Latest Tag
        run: cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Sign the Docker Image with Build Tag
        run: cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:$(date +%d-%m-%Y)

